//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaeControleFrota.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoVeiculo
    {
        public string nomeTipo { get; set; }
        public Nullable<int> numRodas { get; set; }
        public Nullable<int> capacidadePassageiros { get; set; }
        public string carteiraNecessaria { get; set; }
    }
}
