//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaeControleFrota.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veiculo()
        {
            this.LancamentoDiario = new HashSet<LancamentoDiario>();
        }
    
        public string placa { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> ano { get; set; }
        public string familia { get; set; }
        public Nullable<bool> isProprietarioSae { get; set; }
        public Nullable<System.DateTime> inicioVigencia { get; set; }
        public Nullable<System.DateTime> fimVigencia { get; set; }
        public Nullable<int> numContrato { get; set; }
        public Nullable<int> numOrdemCompra { get; set; }
        public Nullable<double> valorLocacao { get; set; }
        public Nullable<double> valorOrdemCompra { get; set; }
        public Nullable<double> saldoOrdemCompra { get; set; }
        public Nullable<double> saldoOcProxMes { get; set; }
        public string proprietario { get; set; }
        public string observacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LancamentoDiario> LancamentoDiario { get; set; }
    }
}
